### ISSUE TITLE
Candela theme: table display too wide

### ISSUE THREAD

**Issue by xolotl** [lumenlearning/candela#57]
A plain vanilla table like below renders full-width with a full-width border. If a table doesn't need to be full-width, it shouldn't be.

The border issue seems to have to do with the `display: block;` in the following style:
``` css
media="screen, print"
table {
  border-collapse: collapse;
  border-spacing: 0;
  max-width: 100%;
  overflow-x: auto;
  display: block;
}
```

``` html
<table cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td>Arch</td>
<td>Pen</td>
</tr>
<tr>
<td>Chowder</td>
<td>Maple</td>
</tr>
<tr>
<td>Airplane</td>
<td>Window</td>
</tr>
<tr>
<td>Kirk</td>
<td>Scotty</td>
</tr>
<tr>
<td>Paper clip</td>
<td>Thumb drive</td>
</tr>
<tr>
<td>Column</td>
<td>Brownies</td>
</tr>
<tr>
<td>Oak</td>
<td>Door</td>
</tr>
<tr>
<td>Subway</td>
<td>Skateboard</td>
</tr>
<tr>
<td>Leia</td>
<td>Cedar</td>
</tr>
<tr>
<td>Fries</td>
<td>Luke</td>
</tr>
</tbody>
</table>
```
![remembering_course_materials___college_orientation_and_success_strategies](https://cloud.githubusercontent.com/assets/997548/8407862/b74ea440-1e1f-11e5-9286-b22f3bfb3140.png)
![remembering_course_materials___college_orientation_and_success_strategies](https://cloud.githubusercontent.com/assets/997548/8407879/d31c64aa-1e1f-11e5-9219-d2658fb6d494.png)
