### ISSUE TITLE
Candela theme (& others?): All H3s unnecessarily centered

### ISSUE THREAD

**Issue by xolotl** [lumenlearning/candela#58]
All H3s are now centered, which makes them hard to parse on a regular page. I think what may have happened is that there was a move to center H3s in decorative boxes that was applied to all H3s.

There is this:
``` css
media="all"
.bcc-box h3:first-child {
  text-align: center;
  margin: -2% -3% 15px;
  color: #ffffff;
  padding: 15px 0 15px;
}
```

And this:
``` css
media="screen, print"
h3 {
  text-align: center;
  font-size: 1em;
  font-weight: bold;
  font-style: normal;
  font-variant: normal;
  text-transform: none;
  letter-spacing: none;
  word-spacing: none;
  page-break-after: avoid;
  hyphens: none;
  -webkit-hyphens: none;
}
```
